server:
  port: 8083

spring:
  application:
    name: affiliation-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5433/made-for-maid-local
    username: anan
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: affiliation_db

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
